config/routes.rb
Rails.application.routes.draw do
  

  resources :clients do
    resources :orders, only: [:index]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :vids
  resources :bodies
  resources :users
  resources :orders, only: [:index, :show, :new, :create, :edit] do
    collection do
      patch 'cgange_add'
      patch 'change_decrement'
    end
  end

  resources :line_items
  resources :carts
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :activation_client, only: [:edit, :update]

  match '/registration', to: 'clients#new' , via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/change_add' => 'orders#change_add', via: 'get'
  match '/change_decrement' => 'orders#change_decrement', via: 'get'
  match '/store' => 'store#index', via: 'get'

  get 'admin' => 'admin#index'
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'session/create'
  get 'session/destroy'

  resources :users

  resources :line_items

  resources :carts

  get 'home/index'
  get 'category/show'

  

  root to: 'home#index', as: 'home'
  
  resources :products do
    get :who_bought, on: :member
  end

  

end

app/models/vid.rb
class Vid < ActiveRecord::Base
end

app/controllers/vids_controller.rb
class VidsController < ApplicationController
  before_action :set_vid, only: [:show, :edit, :update, :destroy]

  # GET /vids
  # GET /vids.json
  def index
    @vids = Vid.all
  end

  # GET /vids/1
  # GET /vids/1.json
  def show
  end

  # GET /vids/new
  def new
    @vid = Vid.new
  end

  # GET /vids/1/edit
  def edit
  end

  # POST /vids
  # POST /vids.json
  def create
    @vid = Vid.new(vid_params)

    respond_to do |format|
      if @vid.save
        format.html { redirect_to @vid, notice: 'Vid was successfully created.' }
        format.json { render :show, status: :created, location: @vid }
      else
        format.html { render :new }
        format.json { render json: @vid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vids/1
  # PATCH/PUT /vids/1.json
  def update
    respond_to do |format|
      if @vid.update(vid_params)
        format.html { redirect_to @vid, notice: 'Vid was successfully updated.' }
        format.json { render :show, status: :ok, location: @vid }
      else
        format.html { render :edit }
        format.json { render json: @vid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vids/1
  # DELETE /vids/1.json
  def destroy
    @vid.destroy
    respond_to do |format|
      format.html { redirect_to vids_url, notice: 'Vid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vid
      @vid = Vid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vid_params
      params.require(:vid).permit(:eat_t)
    end
end

app/helpers/vids_helper.rb
module VidsHelper
end

app/views/vids/_form.html.erb
<%= form_for(@vid) do |f| %>
  <% if @vid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vid.errors.count, "error") %> prohibited this vid from being saved:</h2>

      <ul>
      <% @vid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eat_t %><br>
    <%= f.text_field :eat_t %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vids/edit.html.erb
<h1>Editing vid</h1>

<%= render 'form' %>

<%= link_to 'Show', @vid %> |
<%= link_to 'Back', vids_path %>

app/views/vids/index.html.erb
<h1>Listing vids</h1>

<table>
  <thead>
    <tr>
      <th>Eat t</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vids.each do |vid| %>
      <tr>
        <td><%= vid.eat_t %></td>
        <td><%= link_to 'Show', vid %></td>
        <td><%= link_to 'Edit', edit_vid_path(vid) %></td>
        <td><%= link_to 'Destroy', vid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vid', new_vid_path %>

app/views/vids/new.html.erb
<h1>New vid</h1>

<%= render 'form' %>

<%= link_to 'Back', vids_path %>

app/views/vids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Eat t:</strong>
  <%= @vid.eat_t %>
</p>

<%= link_to 'Edit', edit_vid_path(@vid) %> |
<%= link_to 'Back', vids_path %>