config/routes.rb
Rails.application.routes.draw do
  

  resources :clients do
    resources :orders, only: [:index]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :vids
  resources :bodies
  resources :users
  resources :orders, only: [:index, :show, :new, :create, :edit] do
    collection do
      patch 'cgange_add'
      patch 'change_decrement'
    end
  end

  resources :line_items
  resources :carts
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :activation_client, only: [:edit, :update]

  match '/registration', to: 'clients#new' , via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/change_add' => 'orders#change_add', via: 'get'
  match '/change_decrement' => 'orders#change_decrement', via: 'get'
  match '/store' => 'store#index', via: 'get'

  get 'admin' => 'admin#index'
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'session/create'
  get 'session/destroy'

  resources :users

  resources :line_items

  resources :carts

  get 'home/index'
  get 'category/show'

  

  root to: 'home#index', as: 'home'
  
  resources :products do
    get :who_bought, on: :member
  end

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authorize, only: [:show ] 
  include CurrentCart
  before_action :set_cart
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @is_admin = session_admin?
    @search = @category.products.search(params[:q])
    @products = @search.result(distinct: true)
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_links.html.erb
<div class = "category clearfix">
  <h3>Категории:</h3>
  <% @categories.each do |category| %>
    <%= link_to(category) do %>
      <%= category.title %><br>
    <% end %>
  <% end %>
  <br>
  <h3>Сортировать по:</h3>
  <%= sort_link @search, :title, "Product Name" %><br>
  <%= sort_link @search, :price, "Price" %>
</div><!--/category-->

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit :class => "button middle_green" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<div class="search-products">
<%= search_form_for @search, url: category_path do |f| %>
  <div class="field">
    <%= f.label :title_cont, "Name contains" %>
    <%= f.text_field :title_cont %>
  </div>
  <div class="field">
    <%= f.label :price_gteq, "Price between" %>
    <%= f.text_field :price_gteq %>
    <%= f.label :price_lteq, "and" %>
    <%= f.text_field :price_lteq %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>
</div><!--/search products-->

<%= render 'categories/category_links' %>

<%= render 'products/list' %>

<% if @is_admin %>
	<%= link_to 'Edit', edit_category_path(@category) %> 
	<%= link_to 'Back', categories_path %>
<% end %>