config/routes.rb
Rails.application.routes.draw do
  

  resources :clients do
    resources :orders, only: [:index]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :vids
  resources :bodies
  resources :users
  resources :orders, only: [:index, :show, :new, :create, :edit] do
    collection do
      patch 'cgange_add'
      patch 'change_decrement'
    end
  end

  resources :line_items
  resources :carts
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :activation_client, only: [:edit, :update]

  match '/registration', to: 'clients#new' , via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/change_add' => 'orders#change_add', via: 'get'
  match '/change_decrement' => 'orders#change_decrement', via: 'get'
  match '/store' => 'store#index', via: 'get'

  get 'admin' => 'admin#index'
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'session/create'
  get 'session/destroy'

  resources :users

  resources :line_items

  resources :carts

  get 'home/index'
  get 'category/show'

  

  root to: 'home#index', as: 'home'
  
  resources :products do
    get :who_bought, on: :member
  end

  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_action :authorize, only: [:create, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
	      format.js { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    @cart = Cart.find(session[:cart_id])
    if (!@cart.line_items.exists?)
      render text: "render_home_page"
    else
      render json: { success: true }
    end
    #respond_to do |format|
      #format.html { redirect_to new_order_path, notice: 'Line item was successfully destroyed.' }
      #format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit :class => "button middle_green" %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr id="current_item" data-item_id="<%= line_item.id %>">
<% else %>
  <tr data-item_id="<%= line_item.id %>">
<% end %>
    <td id="quantity-<%= line_item.id %>"><%= line_item.quantity %></td>
    <td><%= line_item.product.title %></td>
    <%# number_to_currency(line_item.total_price) %>
    <td id="item-price-<%= line_item.id %>"><%= line_item.total_price.to_i %></td>
    <td><span class = "add-quantity fa fa-plus-circle link"></span></td> 
    <td><span class = "delete-quantity fa fa-minus-circle link"></span></td>   
    <td><span class = "deleteAction fa fa-trash-o link"></span></td>
  </tr>


      

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s", line_item.quantity, truncate(line_item.product.title, length: 50)) %>

app/views/line_items/create.js.erb
$('#notice').hide();

if ($('#cart tr').lenght == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%= escape_javascript render(@cart) %>");

$('#current_item').css({'background-color':'#88ff88'}).
animate({'background-color':'#114411'}, 1000);

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.id %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>